#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allrun.pre

restore0Dir
runApplication setFields
runParallel -s decompose redistributePar -decompose
runParallel renumberMesh -overwrite
runParallel $(getApplication)
runParallel -s reconstruct redistributePar -reconstruct

rm -r proces*
mkdir run
mv log* run

#------------------------------------------------------------------------------


